---
Name: apiroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'groupon-action': 'GrouponActionController'
    'cart': 'CartController'
    'signup': 'SignupController'
    'signin': 'SigninController'
    'member': 'DashboardController'
    'storist/v1/products': 'StoristProductController'
    'storist/v1/store': 'StoristStoreController'
    'storist/v1/photos': 'StoristPhotoController'
    'storist/v1/manage/$feature': 'StoristManageController'
    'api/v/1/products/$ID': 'ProdctAPI'
    'api/v/1/cloud-products/$ID': 'CloudProductAPI'
    'api/v/1/payment-methods': 'PaymentMethodController'
    'api/v/1/subscribe/$ID': 'SubscribeAPI'
    'api/v/1/freights/$ID': 'FreightAPI'
    'api/v/1/order-items/$ID': 'OrderItemAPI'
    'api/v/1/addresses/$ID': 'AddressAPI'
    'api/v/1/pricings/$ID': 'PricingAPI'
    'api/v/1/variants/$ID': 'VariantAPI'
    'api/v/1/quick/$ID/$todo': 'QuickAPI'
    'api/v/1/ranking/$Barcode': 'RankingAPI'
    'loc-catcher': 'CatcherController'
